[package]
name = "viz-audio"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
viz-core = { workspace = true }
cidre = { workspace = true }
realfft = { workspace = true }
triple_buffer = { workspace = true }
rtrb = { workspace = true }
tracing = { workspace = true }

[lints]
workspace = true
